name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
