name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
