name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build, lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install system dependencies
        run: sudo apt-get install --no-install-recommends -y libdbus-1-dev dbus
      - name: Build
        run: cargo build --verbose
      - name: Run cargo clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose

  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run cargo fmt
        run: cargo fmt --check --verbose
